# Generated by Django 2.2.5 on 2019-09-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cliente_statusentrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cadastro',
            new_name='datacadastro',
        ),
    ]
