# Generated by Django 2.2.5 on 2019-09-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRM', models.CharField(max_length=10, unique=True, verbose_name='CRM')),
                ('nome', models.CharField(max_length=80, verbose_name='Nome')),
            ],
        ),
    ]
